// Questions
var q = [
  "How do you know people want it?",
  "How are you going to do it",
  "What are your users doing now?",
  "How are you processing payments?",
  "How are you managing the risk for merchants?",
  "Who are your ideal customers?",
  "How are planning to meet customers?",
  "Who are your competitors?",
  "How is it different from your competitors?",
  "What is the status of the product and where would you be in the beginning/end of YC?",
  "Why do you think your team has what it takes to win over the market?",
];

var q_ = [
  "What do you understand that others don&#39;t?",
  "Why will you succeed?",
  "How big an opportunity is there?",
  "What problems/hurdles are you anticipating?",
  "Who would use your product?",
  "How much does customer acquisition cost?",
  "How will you make money?",
  "How much money could you make per year?",
  "What is your user growth rate?",
  "How are you meeting customers?",
  "How are you understanding customer needs?",
  "How will you get users?",
  "Who would you hire or how would you add to your team?",

  "So what are you working on?",
  "Do you have a demo?",
  "Where is the rocket science here?",
  "How does your product work in more detail?",
  "How is your product different?",
  "What are you going to do next?",
  "What&#39;s new about what you make?",
  "What, exactly, makes you different from existing options?",
  "Who needs what you&#39;re making?",
  "How do you know customers need what you&#39;re making?",
  "Why isn&#39;t someone already doing this?",
  "What obstacles will you face and how will you overcome them?",
  "How will customers and/or users find out about you?",
  "What resistance will they have to trying you and how will you overcome it?",
  "What are the key things about your field that outsiders don&#39;t understand?",
  "What part of your project are you going to build first?",
  "Who is going to be your first paying customer?",
  "If your startup succeeds, what additional areas might you be able to expand into?",
  "Why did you choose this idea?",
  "What have you learned so far from working on your product?",
  "Six months from now, what&#39;s going to be your biggest problem?",
  "Where do new users come from?",
  "What&#39;s the conversion rate?",
  "What makes new users try you?",
  "Why do the reluctant users hold back?",
  "What are the top things users want?",
  "What has surprised you about user behaviour?",
  "What&#39;s an impressive thing you have done?",
  "What do you understand about your users?",
  "Why did you pick this idea to work on?",
  "What domain expertise do you have?",
  "Who are your competitors?",
  "Who might become competitors?",
  "Someone just showed us an idea like this right before you guys. I don&#39;t like it. What else do you have?",
  "What competition do you fear most?",
  "What is your distribution strategy?",
  "How did your team meet?",
  "Why did your team get together?",
  "Who in your team does what?",
  "Who is &quot;the boss&quot;?",
  "What will you do if we don&#39;t fund you?",
  "How do we know your team will stick together?",
  "What else have you created together?",
  "Are you open to changing your idea? ",
  "What systems have you hacked?",
  "Tell us about a tough problem you solved?",
  "In what ways are you resourceful?",
  "Will you reincorporate as a US company?",
  "Will your team stick at this?",
  "Tell us something surprising you have done?",
  "What&#39;s the funniest thing that has happened to you?",
  "What&#39;s the worst thing that has happened?",
  "What&#39;s the biggest mistake you have made?",
  "What is your burn rate?",
  "How long can you go before funding?",
  "What is the next step with the product evolution?",
  "Have you raised funding?",
  "Who would be your next hire?",

  "How do you know people want this?",
  "What do you know about this space/product others don&#39;t know?",

  "Why are you uniquely qualified to work on this?",
  "Why do you want to dedicate your life to working on this?",
  "How does this become a billion-dollar company?",
  "Why do you trust your partner?",
  "Why do you think he is a good fit to be CEO?",
  "Why do you think he is aa good fit to be CTO?",
  "What keeps you up at night?",
  "Why isn’t someone already doing this?",
  "How can you compete with PayPal and alike, when you don't have the resources?",
  "What are the barriers to entry?",
  "Why doesn't PayPal do it themselves?",
  "Why doesn't Stripe do it themselves?",
  "Why Do you think B2B eCom haven't exploded yet?",
  "How does onboarding during checkout work when onboarding is a required step before even exposing prices or the catalog to the buyer?",
];

// Tips
var tips = ["You're great!"];
